controllers:
    resource:
        path: ../src/Controller/   # 👌 Le dice a Symfony que busque rutas en todos los controladores
        namespace: App\Controller
    type: attribute                # 👌 Usa las anotaciones #[Route] si las tienes

admin_services_duplicate:
    path: /admin/services/duplicate  # 👈 Nueva ruta explícita
    controller: App\Controller\Admin\ServiceController::duplicateServices
