controllers:
    resource:
        path: ../src/Controller/    # Directorio donde se encuentran tus controladores
        namespace: App\Controller    # Espacio de nombres (namespace) de tus controladores
    type: attribute                 # Indica que las rutas deben ser leídas desde los atributos del controlador
