services:
  php_apache_finanzas_hogar:
    build:
      context: .
      dockerfile: ./php_server/Dockerfile
      args:
        NEW_UID: ${NEW_UID}
        NEW_GID: ${NEW_GID}
        MY_USER: ${MY_USER}
        MY_GROUP: ${MY_GROUP}
    container_name: php_apache_finanzas_hogar
    ports:
      - "${PHP_APACHE_PORT}:80"
    volumes:
      - ../.:/var/www/html
    networks:
      - network_finanzas-hogar

  mysql:
    image: mariadb:10.11.9
    container_name: mysql-finanzas-hogar
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./database:/docker-entrypoint-initdb.d
      - persistent-finanzas-hogar:/var/lib/mysql:rw
    depends_on:
      - php_apache_finanzas_hogar
    networks:
      - network_finanzas-hogar

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-finanzas-hogar
    ports:
      - "${PHPMYADMIN_PORT}:80"
    environment:
      PMA_HOST: mysql
    depends_on:
      - mysql
    networks:
      - network_finanzas-hogar

networks:
  network_finanzas-hogar:
    name: network_finanzas-hogar

volumes:
  persistent-finanzas-hogar:
